name: run_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^9.0.2
  intl: ^0.18.0


  cupertino_icons: ^1.0.2
  flutter_tts: ^3.6.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.5+1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  equatable: ^2.0.5
  dio: ^5.1.2
  stack_trace: ^1.11.0
  flutter_riverpod: ^2.3.6
  dio_smart_retry: ^5.0.0
  shared_preferences: ^2.1.2
  wakelock: ^0.6.2
  flutter_secure_storage: ^8.0.0
  email_validator: ^2.1.17
  quickalert: ^1.0.1
  flutter_spinkit: ^5.2.0
  coverage: ^1.6.3
  mockito: ^5.4.2
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.15
  esys_flutter_share_plus: ^2.2.0
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  generate: true

